// Code generated by protoc-gen-go. DO NOT EDIT.
// source: delta.proto

package crdt_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Delta struct {
	Elements             []*Element `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	Tombstones           []*Element `protobuf:"bytes,2,rep,name=tombstones,proto3" json:"tombstones,omitempty"`
	Height               uint64     `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Topic                string     `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Delta) Reset()         { *m = Delta{} }
func (m *Delta) String() string { return proto.CompactTextString(m) }
func (*Delta) ProtoMessage()    {}
func (*Delta) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9f1fd9d66f078a0, []int{0}
}

func (m *Delta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delta.Unmarshal(m, b)
}
func (m *Delta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delta.Marshal(b, m, deterministic)
}
func (m *Delta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delta.Merge(m, src)
}
func (m *Delta) XXX_Size() int {
	return xxx_messageInfo_Delta.Size(m)
}
func (m *Delta) XXX_DiscardUnknown() {
	xxx_messageInfo_Delta.DiscardUnknown(m)
}

var xxx_messageInfo_Delta proto.InternalMessageInfo

func (m *Delta) GetElements() []*Element {
	if m != nil {
		return m.Elements
	}
	return nil
}

func (m *Delta) GetTombstones() []*Element {
	if m != nil {
		return m.Tombstones
	}
	return nil
}

func (m *Delta) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Delta) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type Element struct {
	Cid                  string   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Block                string   `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	Rmin                 int32    `protobuf:"varint,4,opt,name=rmin,proto3" json:"rmin,omitempty"`
	Rmax                 int32    `protobuf:"varint,5,opt,name=rmax,proto3" json:"rmax,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	ShardSize            uint64   `protobuf:"varint,7,opt,name=shard_size,json=shardSize,proto3" json:"shard_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Element) Reset()         { *m = Element{} }
func (m *Element) String() string { return proto.CompactTextString(m) }
func (*Element) ProtoMessage()    {}
func (*Element) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9f1fd9d66f078a0, []int{1}
}

func (m *Element) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Element.Unmarshal(m, b)
}
func (m *Element) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Element.Marshal(b, m, deterministic)
}
func (m *Element) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Element.Merge(m, src)
}
func (m *Element) XXX_Size() int {
	return xxx_messageInfo_Element.Size(m)
}
func (m *Element) XXX_DiscardUnknown() {
	xxx_messageInfo_Element.DiscardUnknown(m)
}

var xxx_messageInfo_Element proto.InternalMessageInfo

func (m *Element) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *Element) GetBlock() string {
	if m != nil {
		return m.Block
	}
	return ""
}

func (m *Element) GetRmin() int32 {
	if m != nil {
		return m.Rmin
	}
	return 0
}

func (m *Element) GetRmax() int32 {
	if m != nil {
		return m.Rmax
	}
	return 0
}

func (m *Element) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Element) GetShardSize() uint64 {
	if m != nil {
		return m.ShardSize
	}
	return 0
}

func init() {
	proto.RegisterType((*Delta)(nil), "crdt.pb.Delta")
	proto.RegisterType((*Element)(nil), "crdt.pb.Element")
}

func init() { proto.RegisterFile("delta.proto", fileDescriptor_c9f1fd9d66f078a0) }

var fileDescriptor_c9f1fd9d66f078a0 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4b, 0x4a, 0xc4, 0x40,
	0x10, 0x86, 0xe9, 0xc9, 0xcb, 0xa9, 0xd9, 0x0c, 0x85, 0x48, 0x6d, 0x84, 0x30, 0xab, 0x2c, 0x24,
	0x88, 0x5e, 0x41, 0x2f, 0x10, 0x0f, 0x20, 0x9d, 0xa4, 0x30, 0x8d, 0x49, 0x3a, 0xa4, 0x6b, 0x31,
	0xcc, 0x19, 0xdc, 0x7a, 0x5f, 0x49, 0x25, 0x8a, 0x9b, 0xd9, 0xfd, 0x8f, 0xef, 0x2f, 0x9a, 0x86,
	0x43, 0xcb, 0xbd, 0xd8, 0x72, 0x9a, 0xbd, 0x78, 0xcc, 0x9a, 0xb9, 0x95, 0x72, 0xaa, 0x4f, 0xdf,
	0x06, 0x92, 0x97, 0xa5, 0xc0, 0x07, 0xb8, 0xe1, 0x9e, 0x07, 0x1e, 0x25, 0x90, 0xc9, 0xa3, 0xe2,
	0xf0, 0x74, 0x2c, 0x37, 0xaa, 0x7c, 0x5d, 0x8b, 0xea, 0x8f, 0xc0, 0x47, 0x00, 0xf1, 0x43, 0x1d,
	0xc4, 0x8f, 0x1c, 0x68, 0x77, 0x85, 0xff, 0xc7, 0xe0, 0x1d, 0xa4, 0x1d, 0xbb, 0x8f, 0x4e, 0x28,
	0xca, 0x4d, 0x11, 0x57, 0x9b, 0xc3, 0x5b, 0x48, 0xc4, 0x4f, 0xae, 0xa1, 0x38, 0x37, 0xc5, 0xbe,
	0x5a, 0xcd, 0xe9, 0xcb, 0x40, 0xb6, 0x5d, 0xc1, 0x23, 0x44, 0x8d, 0x6b, 0xc9, 0x68, 0xbf, 0xc8,
	0x65, 0x53, 0xf7, 0xbe, 0xf9, 0xa4, 0xdd, 0xba, 0x51, 0x83, 0x08, 0xf1, 0x3c, 0xb8, 0x51, 0x0f,
	0x25, 0x95, 0xea, 0x35, 0xb3, 0x67, 0x4a, 0x7e, 0x33, 0x7b, 0x5e, 0xb2, 0xd1, 0x0e, 0x4c, 0xa9,
	0x8e, 0x55, 0xe3, 0x3d, 0x40, 0xe8, 0xec, 0xdc, 0xbe, 0x07, 0x77, 0x61, 0xca, 0xf4, 0x85, 0x7b,
	0x4d, 0xde, 0xdc, 0x85, 0xeb, 0x54, 0xbf, 0xed, 0xf9, 0x27, 0x00, 0x00, 0xff, 0xff, 0x1f, 0xab,
	0x0c, 0x8b, 0x45, 0x01, 0x00, 0x00,
}
